### PR TITLE
flirpi: make it cross-compilable

### PR DESCRIPTION
**Pull request by artemysfr**

### CODE REVIEW

**Comment by kekiefer** [comment]
Thanks for the updates! This changes look fine to me. Any issues from other watchers?

**Comment by israelshirk** [comment]
LGTM.  I always end up changing the hardcoded spidev0.0 to spidev1.0 or some other, but I think that's out of scope here.

**Comment by artemysfr** [comment]
hum... seems like everything I commit on my clone's branch end up here as pull request... at the moment, only the first 2 commits were intended to be merged as is and serve as a test to see if this respository is still active ;-)
Of course if last third commits are OK for you, you can also take them. They are tested and working well here on Armadeus embedded SOMs (cross-compiled with Buildroot).

**Comment by kekiefer** [comment]
Since it was not really the intent, I'll merge just the first two commits and if anyone comes across this PR and wants the other ones, leave a note and we'll revisit

**Pull request closed without merging**
