### PR TITLE
Image save and additional color modes for raspberrypi_video

### PR DESCRIPTION
**Pull request by Cullpepper**
Updates collected from the google forum: https://groups.google.com/forum/#!topic/flir-lepton/MTS7x3rRQ9w

### CODE REVIEW

**Comment by kekiefer** [comment]
I'd like to see the changes properly documented in the commit message, and please don't add whitespace changes or trivial changes (deleting comments for example) to the commit.

@MartyMacGyver or anyone else with write access and a working Lepton setup right now any comments?

**Comment by MartyMacGyver** [comment]
I don't have a setup handy right at the moment but I still have some basic questions about this:

- What problem is all of this solving? I'm not against new functionality, but I'm trying to understand the use case and expectations for this
- Why is the output image is being re-scaled? Maybe give the user an option to select the rescaling factor
- Output to the cwd or home dir of the current user (~/.)... don't assume /home/pi
- The thread contained a suggestion to append a timestamp to the snapshot to avoid name collisions - that seems like it'd be quite useful if one is outputting snapshots in this way
- An unrelated comment was removed
- The files should end on a new line

**Comment by Cullpepper** [comment]
Sorry, this is all new to me. This is my first project with a Lepton, my
first project using Python and my first attempt at submitting code to
Github, so I apologize if I'm doing it all wrong.

> I don't have a setup handy right at the moment but I still have some basic
> questions about this:
>
>    - What problem is all of this solving? I'm not against new
>    functionality, but I'm trying to understand the use case and expectations
>    for this
>
> I'm doing a hackathon right now to try to build something with the Lepton.
I'm working on headless raspberrypi, running off a battery pack, that's in
ttende to capture thermal data for motion detection and gesture
recognition.

The two scripts I uploaded were my first attempts to grab the sensor data
and manipulate it.

pylepton_livefeed is different from pylepton_overlay in that it doesn't
require a picamera to function.

pylepton_snapshot is probably not different enough from pylepton_capture to
be useful, but for a noob like me, having a tool that functions more like a
classic screengrab is helpful.

>
>    - Why is the output image is being re-scaled? Maybe give the user an
>    option to select the rescaling factor
>
> Oh, shoot, that junk code. I have another more developed version of this
that's applying HOG image detection to identify people objects in the
frame.

>
>    - Output to the cwd or home dir of the current user (~/.)... don't
>    assume /home/pi
>    - The thread contained a suggestion to append a timestamp to the
>    snapshot to avoid name collisions - that seems like it'd be quite useful if
>    one is outputting snapshots in this way
>    - An unrelated comment was removed
>    - The files should end on a new line
>
> I can see now that this is not finished enough for a pull request. I think
I'll hold off until I have my final project done (a lepton-based people/car
counter).

Thanks for your comments.

best,
-Cullen

**Comment by kekiefer** [comment]
@Cullpepper please note this is a different pull request than we were discussing earlier. This is groupgets/LeptonModule (not groupgets/pylepton) -- you submitted this PR a couple weeks ago.

**Comment by Cullpepper** [comment]
Ah. oops. Sorry. New guy.

I'll stop with the github stuff until I get a better understanding of how
it works.

**Comment by DanDawson** [comment]
@Cullpepper I'm not a GitHub expert either, but I applaud your willingness to help out with this project, and jumping in to the world of submitting code to open source projects can be a bit overwhelming at first, so don't get discouraged. 

What I recommend doing is take a look at commits by other people on this project and on other GitHub projects. Try to look for things they have in common, good descriptive commit messages, perhaps having a pull request relate to only one feature addition or change... probably best not to group a bunch of unrelated updates together in to one pull request because it is harder to figure out what's going on, harder to fix any bugs introduced since they are changing a lot of different things.

I haven't gone through all of your requested updates, but make sure the updates you add here are for the good of the whole project, and not items related specifically to one use case or one specific project. 

Branches are perfect for that, when you're customizing it for your own project, then it's still available for people to review and figure out if your modifications will help there project or if they should be brought back in to the master branch.

Again, I'm not an expert, so those more experienced can offer you more information, but if you have any questions feel free to ask me and I can  try to figure out the answers if I don't know them.

Welcome to the world of open source, don't get discouraged, and good luck!

@DanDawson, support@ddhosting.net

**Comment by Cullpepper** [comment]
Thank you, I got excited and jumped in too soon.

**Comment by MartyMacGyver** [comment]
@Cullpepper Understand, I'm certainly intrigued by your code changes, but from my perspective they just need some refinement so they integrate well with the code base and user experience.

That said, the Pi can be tricky when it comes to the Lepton thanks to the way interrupts happen in Linux (and the sensitivity of the Lepton to the SPI comms interruptions). Good luck!

**Comment by Cullpepper** [comment]
Thanks - I'll be back when I have something production-ready. My ultimate
goal is a thermal blob counter that picks out humans, so interrupts are
less important for me - the histogram over time is what will count for my
user display (rather than the feed itself.)

I'll put it all up when I'm done.

best,
-Cullen

**Pull request closed without merging**
